{% set name = "mnelab" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd057c2e7500cfb7e6117863d3cf039c396563e0011791f6f313fa20d58918cd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: true
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - python.app                      # [osx]
    - pyobjc-framework-cocoa >=10.0   # [osx]
    - mne-base >=1.6.0
    - matplotlib-base >=3.8.0
    - numpy >=1.25.0
    - scipy >=1.10.0
    - pyxdf >=1.16.4
    - pyside6 >=6.6.0
    - scikit-learn >=1.3.0
    - python-picard >=0.7.0
    - pyedflib >=0.1.35
    - pybv >=0.7.4

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
