{% set name = "mnelab" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39bc8a38f7a71fa70661ba19c61774fff3bf0d2bc5d74349c1b711f4531fbdfa

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: True
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python.app              # [osx]
    - pyobjc-framework-cocoa  # [osx]
    - matplotlib >=2.0.0
    - mne >=0.17.1
    - numpy >=1.8.1
    - pybv
    - pyedflib
    - pyqt >=5.6.0
    - python-picard
    - pyxdf
    - scikit-learn
    - scipy >=0.17.1

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.'

extra:
  recipe-maintainers:
    - hoechenberger
