{% set name = "mnelab" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b31ba19614e1e8ec5ac44f5e6bceb6a4d35c4c35414d9dd5b4351c00f52c642

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: true
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python.app                    # [osx]
    - pyobjc-framework-cocoa >=7.3.0  # [osx]
    - mne-base >=1.0.0
    - matplotlib-base >=3.5.0
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pyxdf >=1.16.0
    - pyside6 >=6.2.0
    - scikit-learn >=1.0.0
    - python-picard >=0.7.0
    - pyedflib >=0.1.22
    - pybv >=0.7.4

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - hoechenberger
