{% set name = "mnelab" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b99affb51c9bba86e6fc765ca4455b5cf519d1869cc2ef6ab0bcfe2cafa2c06f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: true
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - python.app                    # [osx]
    - pyobjc-framework-cocoa >=7.1  # [osx]
    - mne-base >=0.22.0
    - matplotlib-base >=2.1
    - numpy >=1.14.0
    - pybv >=0.4.0
    - pyedflib >=0.1.15
    - python-picard >=0.4.0
    - pyxdf >=1.16.0
    - scikit-learn >=0.20.0
    - scipy >=1.0.0
    - pyqt >=5.10.0
    - qtpy >=1.9.0

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - hoechenberger
