{% set name = "mnelab" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e89e249855824a2ef5dd7244b7ac4e66b12ffc94f164bb10b6125533953106fe

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: true
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python.app                      # [osx]
    - pyobjc-framework-cocoa >=5.2.0  # [osx]
    - matplotlib-base >=2.1
    - mne >=0.20
    - numpy >=1.14.0
    - pebble >=4.5.0
    - pybv
    - pyedflib
    - python-picard
    - pyxdf
    - scikit-learn
    - scipy >=1.0.0
    - qtpy >=1.9.0

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - hoechenberger
