{% set name = "mnelab" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cd94b74e9f41a69f08ee34bbe15aefe543c780ac7ac8571eab599529c0ac970

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: true
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - python.app                    # [osx]
    - pyobjc-framework-cocoa >=7.3.0  # [osx]
    - mne-base >=1.0.0
    - matplotlib-base >=3.6.2
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pyxdf >=1.16.0
    - pyside6 >=6.2.0
    - scikit-learn >=1.0.0
    - python-picard >=0.7.0
    - pyedflib >=0.1.22
    - pybv >=0.7.4

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
