{% set name = "mnelab" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f0b75ea9082e97119e8caefbbda0f9e0459d60d18c10ef5b3c19daf748d18dc

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: true
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python.app                      # [osx]
    - pyobjc-framework-cocoa >=5.2.0  # [osx]
    - matplotlib-base >=2.1
    - mne >=0.21                      # [py <39]
    - mne >=0.22                      # [py >=39]
    - numpy >=1.14.0
    - pebble >=4.5.0
    - pybv
    - pyedflib
    - python-picard
    - pyxdf
    - scikit-learn
    - scipy >=1.0.0
    - qtpy >=1.9.0

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - hoechenberger
