{% set name = "mnelab" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d8e515e9f7034870be9be3eaf777642780971ae95c32913fe836bfc2cdb5931

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  noarch: python
  osx_is_app: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - python.app                      # [osx]
    - pyobjc-framework-cocoa >=10.0   # [osx]
    - edfio >=0.4.2
    - matplotlib-base >=3.8.0
    - mne-base >=1.7.0
    - mne-qt-browser >=0.6.2
    - numpy >=2.0.0
    - scipy >=1.14.1
    - pyxdf >=1.16.4
    - pyside6 >=6.7.1
    - scikit-learn >=1.3.0
    - python-picard >=0.8.0
    - pybv >=0.7.4

test:
  imports:
    - mnelab
    - mnelab.utils
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import mnelab; assert mnelab.__version__ == '{{ version }}', mnelab.__version__"

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
