{% set name = "mnelab" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6fe594d13bc0f96f01b41fc00e12d90a9904704094db504e7c37b1d3ae0e010

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mnelab = mnelab.__main__:main
  osx_is_app: true
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - python.app                      # [osx]
    - pyobjc-framework-cocoa >=10.0   # [osx]
    - mne-base >=1.6.0
    - matplotlib-base >=3.8.0
    - numpy >=1.25.0
    - scipy >=1.10.0
    - pyxdf >=1.16.4
    - pyside6 >=6.6.0
    - scikit-learn >=1.3.0
    - python-picard >=0.7.0
    - pyedflib >=0.1.35
    - pybv >=0.7.4

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
