travis:
  secure:
    BINSTAR_TOKEN: 6E2d2bi2uKF9gQLfs5vnthI6Ug4SEdE/0wZpTjDtkSCMf7USF7liZCEkwlWAKfAsv27tvpDFx4ZuJPNzE4X45tuD8e2erI9DzfaXnt55IAf1xKtbXyuvy5FAG1snl79DvY2VYUVi7AAqSwm5gGhN2dq33EZtaB1JlbFRGnZ7MZRj/+i2HPqDmJROM8Dh99XkwIs2jVgWxYfKJvaHMul1iF9zZDovQ024IimlDqvA8QvXbjrmykdTlAFNhT+reZVkpz1fOeuM2IkkcAJ1qygb7wiu9Za21LTK+Uihtt4J+2Q65/pkqrkh1Q1Qg/afRGnkrAAynfhi5s9EqY78zuuWWWWUVPZMC4CWjXU02LfHniNcX4b3m7ZjVc2jooQ4OJufxWHDUHlTO/jckEMN1CrutP96K2yMWyMDZCUX3H6rUr/Yf8Ln1myT/4RjJfq3dUlSGBDibH+mH0jHr9lRM2tmunMUN8lufuJyraSRwKB1cn9HEQMwZQqhpVAfWOCwTBpCuyTa469WW2h6CJiUM4bGL24bl5KWDwq6gRjjkXnstRfu64n068dGY8ynIE8r81iYxnGwS38q9rfRTslYo0p8Uszkl56DyefXfMSVao6UI5ra3LKFCNc28rG8XpkyGn/Lrwsqaq8jmuVJba2tiNYiQJrA/UvTUeBmFvG1krT9+Oo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
